<?php

/**
 * ACCESS TOKEN TYPE
 */
define('OAUTH3LEGGED_CLIENT_ACCESS_TOKEN_TYPE', 0);

/**
 * REQUEST TOKEN TYPE
 */
define('OAUTH3LEGGED_CLIENT_REQUEST_TOKEN_TYPE', 1);


/**
 * Implements hook_menu().
 */
function oauth3legged_client_menu() {
  $items = array();

  // Put your menu items here.
  $items['oauthclient/oauth'] = array(
    'title' => 'Oauth client',
    'page callback' => 'oauthclient_3legged_oauth',
    'page arguments' => array(2,3), //2 should be uid, 3 should be udid
    'access callback' => 'oauthclient_access',
    'access arguments' => array(2,3), //Defaults to user_access
  );

  $items['admin/config/services/oauth3legged_client'] = array(
    'title' => 'Mobingi Consumer Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oauth3legged_client_admin'),
    'access arguments' => array('administer mobingi consumer.'),
    'file' => 'oauth3legged_client.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/oauth3legged_client/settings'] = array(
    'title' => 'Mobingi Consumer Configuration',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['admin/config/services/oauth3legged_client/example'] = array(
    'title' => 'Example',
    'page arguments' => array('oauth3legged_client_example'),
    'access arguments' => array('administer mobingi consumer.'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  $items['admin/config/services/oauth3legged_client/example/create_user'] = array(
    'title' => 'Create user',
    'page callback' => 'oauth3legged_client_create_user',
    'access arguments' => array('mobingi create user'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function oauth3legged_client_permission() {
  return array(
    'administer oauth3legged_client module' => array(
        'title' => t('Administer Mobingi Consumer'),
        'description' => t('Configuration for App Key and App Secret.'),
      ),
    'mobingi create user' => array(
        'title' => t('Create Mobingi user'),
        'description' => t('Remotely create Mobingi user.'),
      ),
  );
}

/*
 * @param $uid, $udid (from mobile phone)
 * @return true if user / udid found in database
 */
function oauthclient_access($uid, $udid) {
  // TO-Do Denied user if the UDID & uid not found in database
  if ($uid > 0)
    return TRUE;

  //Only using in mobingi, should have other non-password security measure
  if ($uid == 'authenticated' && $udid == 'token')
    return TRUE;
  else 
    return FALSE;
}

/**
 * Create Mobingi user.
 *
 * @param $external_id is UDID in our case.
 * @return An array of token key and secret
 *   - token_key OAuth token key.
 *   - token_secret OAuth token secret.
 */
function oauth3legged_client_create_user($name, $pass, $mail, $external_id = NULL) {
  $settings = variable_get('oauth3legged_client', _oauth3legged_client_default());

  $request_url = $settings['provider']['url'] . '/' . $settings['provider']['endpoint'] . '/user.json';

  // 2-legged OAuth
  try {
    $oauth = new OAuth($settings['provider']['consumer_key'], $settings['provider']['consumer_secret'], OAUTH_SIG_METHOD_HMACSHA1, OAUTH_AUTH_TYPE_URI);
    header('Content-Type: application/json');
    $oauth->fetch($request_url, array(
      'name' => $name . '_' . $external_id,
      'pass' => $pass,
      'mail' => $mail,
    ), OAUTH_HTTP_METHOD_POST);
    $response = $oauth->getLastResponse();
    $json = json_decode($response);
    return TRUE;
  } catch(OAuthException $E) {
    return FALSE;
  }
}

/**
 * Default settings value.
 */
function _oauth3legged_client_default() {
  return array(
    'fields' => array(
      'token_key' => '',
      'token_secret' => '',
      'token_type' => '',
    ),
    'provider' => array(
      'url' => '',
      'endpoint' => '',
      'consumer_key' => '',
      'consumer_secret' => '',
    ),
  );
}

/**
 * Helper function for calling oauth server.
 * Require sending uid from client 
 *
 * @param $uid
 *    (required) User ID.
 * @param $external_id
 *    (optional) External ID, i.e. udid.
 */
function oauthclient_3legged_oauth($uid, $external_id = NULL) {
  // get the settings value.
  $settings = variable_get('oauth3legged_client', _oauth3legged_client_default());

  // build urls.
  $oauth_provider_url = $settings['provider']['url'];
  if ( valid_url($oauth_provider_url) ) {
    $request_token_url = $oauth_provider_url.'/oauth/request_token'; //To-DO read from admin form
    $access_token_url = $oauth_provider_url.'/oauth/access_token';
    $authorize_url = $oauth_provider_url.'/oauth/authorize';
  }
  $consumer_key = $settings['provider']['consumer_key'];
  $consumer_secret = $settings['provider']['consumer_secret'];

  // start OAuth
  $oauth = new OAuth($consumer_key, $consumer_secret, OAUTH_SIG_METHOD_HMACSHA1, OAUTH_AUTH_TYPE_URI);
  $oauth->enableDebug(); // let you know when and why some request fails

  $user = user_load($uid);
  $user_wrapper = entity_metadata_wrapper('user', $user);
  if (empty($user->{$settings['fields']['token_secret']})) {
    $request_token_array = $oauth->getRequestToken($request_token_url);
    $user->{$settings['fields']['token_key']}->set($request_token_array['oauth_token']);
    $user->{$settings['fields']['token_secret']}->set($request_token_array['oauth_token_secret']);
    $user->save();

    // mapping ids with request token
    $ids = array (
      'uid' => $uid,
      'udid' => $udid,
    );
    variable_set($_SESSION['request_token'], $ids);

    // takes you to Drupal authorize page
    drupal_goto($authorize_url.'?oauth_token='.$_SESSION['request_token']);
  } else if (empty($_SESSION['access_token'])) { // continues below
    // PHP still needs the request token/secret to get the access token and secret
    $request_token_secret = $_SESSION['request_token_secret']; 
    $oauth->setToken($_REQUEST['oauth_token'],$request_token_secret);

    $access_token_info = $oauth->getAccessToken($access_token_url);
    $_SESSION['access_token']= $access_token_info['oauth_token'];
    $_SESSION['access_token_secret']= $access_token_info['oauth_token_secret'];
  }

  /*
  if (isset ($_SESSION['access_token'])) {
    //Set access_token and consume service
    $access_token = $_SESSION['access_token'];
    $access_token_secret =$_SESSION['access_token_secret'];
    $oauth->setToken($access_token,$access_token_secret);
    $access_token_array = array (
        'access_token' => $access_token,
        'access_token_secret' => $access_token_secret,
        );
    //Mapping request token with ids
    $ids_to_load = variable_get($_SESSION['request_token']);
    $uid_to_load = $ids_to_load['uid'];
    $udid_to_load = $ids_to_load['udid'];
    //To-DO save the access token to user profile, after logged in with 2legged
    if ($user = user_load($uid_to_load) )
      variable_set($user->uid.'_'.$udid_to_load.'_oauthsecret', $access_token_array);
    print_r($access_token_array);
    drupal_set_message('Saving access_token ok!');

    // For ios: Execute DIOS schema
    $dios = convertCurrentURL();
    drupal_set_message($dios);
    header("Location: ".$dios."success_dios");
    //Verify the tokens
    $req_header = array(
      'Accept'=>"application/json",
      'format'=>"json"
    );

    //With access_token, you can consume all enabled resource, here just a demo
    $resource_url = 'http://dev-oapi.mobingi.com/mobi/rest/node/1.json';
    //Consume web service
    try {
      $data = $oauth->fetch($resource_url,null,OAUTH_HTTP_METHOD_GET,$req_header);

      if ($data) {
        $response_info = $oauth->getLastResponse();
        return "Your access_token is saved, you can now use it to consume web services";
      } else {
        return "Get access_token failed";
      }
    }
    catch(Exception $e) {
      //echo $e->getCode(); // 401
      // Message generated by OAuth class
      echo $e->getMessage(); // Invalid auth/bad request (got a 401, expected HTTP/1.1 20X or a redirect)
      // Message returned
      echo $e->lastResponse; // {"errors":[{"message":"Could not authenticate you","code":32}]}
    }
  }
   */
}

//Helper function to convery current url to dios:
function convertCurrentURL() {
 $pageURL = 'http';
 if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
 $pageURL .= "://";
 if ($_SERVER["SERVER_PORT"] != "80") {
  $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
 } else {
  $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 }

  return str_replace("http://", "dios://", $pageURL);
}
